framework:
    messenger:
        transports:
            import: "%env(MESSENGER_TRANSPORT_IMPORT_DSN)%"
            export: "%env(MESSENGER_TRANSPORT_EXPORT_DSN)%"
            core: "%env(MESSENGER_TRANSPORT_CORE_DSN)%"
            segment: "%env(MESSENGER_TRANSPORT_SEGMENT_DSN)%"
            completeness: "%env(MESSENGER_TRANSPORT_COMPLETENESS_DSN)%"
            notification: "%env(MESSENGER_TRANSPORT_NOTIFICATION_DSN)%"

ergonode_category:
    messenger:
        transport_name: 'core'

ergonode_completeness:
    messenger:
        transport_name: 'completeness'

ergonode_designer:
    messenger:
        transport_name: 'core'

ergonode_channel:
    messenger:
        transport_name: 'export'

ergonode_exporter_file:
    messenger:
        transport_name: 'export'

ergonode_exporter_shopware6:
    messenger:
        transport_name: 'export'

ergonode_mailer:
    messenger:
        transport_name: 'notification'

ergonode_importer:
    messenger:
        transport_name: 'import'

ergonode_segment:
    messenger:
        transport_name: 'segment'

